### ISSUE TITLE
Typo in png

### ISSUE THREAD

**Issue by guettli** [dntosas/capi2argo-cluster-operator#154]
There is a tiny typo in the doc:

https://github.com/dntosas/capi2argo-cluster-operator/blob/main/docs/flow-with-operator.png

In the image it is "9. Convert".

But it needs to be "7. Convert".

BTW: Thank you very much for the great introduction and the image which explains the workflow!

**Comment by dntosas** [comment]
Thnx @guettli ! Fixed in https://github.com/dntosas/capi2argo-cluster-operator/commit/4926908e134a78f8c8c70956eee81b0ade5da901
