### ISSUE TITLE
secret for deleted cluster not removed

### ISSUE THREAD

**Issue by mstarostik** [dntosas/capi2argo-cluster-operator#164]
Testing creation and destruction of clusters via ArgoCD including the management of those clusters with the help of this operator, I noticed that deleting a CAPI cluster entirely (The whole namespace with the Cluster resource as well as the CAPI secret is gone), the cluster remains configured to ArgoCD and the secret that was successfully generated by CACO is not removed.

**Comment by dntosas** [comment]
Hey!

Yeap, this is true, Garbage collection is on the roadmap for v0.2.0 ^

**Comment by dntosas** [comment]
WIP in https://github.com/dntosas/capi2argo-cluster-operator/pull/166

**Comment by dntosas** [comment]
@mstarostik FYI this is now merged and released (v0.1.12) as part of https://github.com/dntosas/capi2argo-cluster-operator/pull/166

enjoy :)

**Comment by mstarostik** [comment]
Thanks a lot, works nicely!
