### ISSUE TITLE
Question:  does it do an 'argocd cluster add'?

### ISSUE THREAD

**Issue by lknite** [dntosas/capi2argo-cluster-operator#195]
The description sounds like it syncs the passwords and that is all, but when you do an argocd cluster add it looks to install a service account as well.

If you sync the secrets only does it automatically install a service account later on when it needs it?

Or do you in fact use 'argocd cluster add' behind the scene?

**Comment by dntosas** [comment]
hey!

Nop, here we don't simulate the behavior of `argocd cluster add` behavior 1-1, we are just providing a simple integration for declarative setup when going with Argo + CAPI ^^

Nevertheless, creating a service-account and limiting the RBAC perms on new created secret would be a nice addition if you would like to contribute it, I would love to help if needed :)

**Comment by lknite** [comment]
It seems like a good idea to exec into the argocd-server pod and run 'argocd cluster add' there.  I can't think of a reason why that isn't a good idea other than it seems to require generating and providing an apiKey.  What do you think?

I'm probably going to end up writing another solution cause I have a few more requirements...

**Comment by lknite** [comment]
thank you
